#!/usr/bin/perl

use strict;
use warnings;

use File::Find;
use Path::Class;

print <<_END_;
package Blog::Bluejay::Assets::Data::Source;
1;
__DATA__
_END_

find( { no_chdir => 1, wanted => sub {
    my $path = $_;
    return ($File::Find::prune = 1) if
        $path =~ m!^assets/document! ||
        $path =~ m!\btt/mock! ||
        $path =~ m/\.sw.$/ ||
        $path =~ m{^assets/.protect$} ||
        0
    ;
    return unless -f $path;
    my $file = file $path;
    print "$file\n";
    print scalar $file->slurp;
    print "__ASSET__\n";
} }, 'assets' );
