#!/usr/bin/perl

use strict;
use warnings;

use File::Find;
use Path::Class;

print <<_END_;
package Blog::Bluejay::Assets::Data::Source;
1;
__DATA__
_END_

find( { no_chdir => 1, wanted => sub {
    my $path = $_;
    return ($File::Find::prune = 1) if
        $path =~ m!^assets/document! or
        $path =~ m!\btt/mock! or
        $path =~ m/\.sw.$/ or
        $path =~ m{^assets/.protect$} or
        ($path =~ m{^script/.+} and $path !~ m{script/blog_}) or
        0
    ;
    return unless -f $path;
    my $file = file $path;
    print "$file\n";
    print scalar $file->slurp;
    print "__ASSET__\n";
} }, qw/script assets/ );
