#!/usr/bin/perl -w

use strict;
use warnings;

use Path::Class;
use Document::TriPart::Cabinet;

#die "Don't have an environment... did you source ./script/env?\n" unless $ENV{BLOG_BLUEJAY};

my $class;
my @bluejay;
eval {
    require Project::b9::FindAppHome;
    require Project::b9::Environment;
    $class = 'Project::b9';
    push @bluejay, home => Project::b9::FindAppHome->find;
};
$class ||= 'Blog::Bluejay';

eval "require $class;" or die $@;

my $bluejay = $class->new( @bluejay );
my $journal = $bluejay->journal;
my $cabinet = $bluejay->cabinet;

my $dir = dir 'legacy-cabinet';
for (grep { -f $_ } $dir->children) {
    next unless $_->basename =~ m/^($Document::TriPart::Cabinet::UUID::re)$/;
    my $uuid = $1;
    my $legacy_document = $_;
    my $legacy_assets = $dir->file( "${uuid}_assets" );

    my $document_dir = $cabinet->storage->document_dir( $uuid );
    my $document_file = $cabinet->storage->document_file( $uuid );
    my $assets_dir = $cabinet->storage->assets_dir( $uuid );

    $document_dir->mkpath unless -d $document_dir;
    
    print "$uuid => $_ into $document_file\n";

#    my $document = Document::TriPart->new( file => $legacy_document );
#    my $document = Document::TriPart::Cabinet::Document->new( uuid => $uuid,  );
    my $document = $cabinet->create( uuid => $uuid );
    $document->_tp->read( $legacy_document );
    my $status = delete $document->header->{folder};
    $status = $status eq 'journal' ? 'published' : undef if $status;
    $document->header->{creation} = delete $document->header->{cdtime};
    $document->header->{modification} = delete $document->header->{mdtime} if exists $document->header->{mdtime};
    $document->header->{status} = $status if defined $status;
    $document->save;

#    $cabinet->save( $document );

#    system( "rsync -av $legacy_document $document_file" );

    system( "rsync -av $legacy_assets/ $assets_dir/" ) if -d $legacy_assets;
}
